name: achref_siaha
description: Un nouveau projet Flutter.

# La ligne suivante empêche le package d'être publié accidentellement sur
# pub.dev en utilisant `flutter pub publish`. C'est préférable pour les packages privés.
publish_to: 'none' # Supprimez cette ligne si vous souhaitez publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.4
  intl_phone_number_input: ^0.7.2
  get: ^4.2.4
  cached_network_image: ^3.2.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  intl: ^0.17.0
  date_time_picker: ^2.1.0
  google_maps_flutter: ^2.3.0
  # flutter_osm_plugin: ^0.50.0
  # flutter_open_street_map: ^0.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_fonts: ^3.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_native_splash:
  # Configuration de l'écran de démarrage natif
  color: "#FFFFFF" # Couleur de fond pour la plateforme Android et iOS
  image: "assets/splash.png" # Chemin vers l'image à utiliser comme écran de démarrage
  android: true # Activer l'écran de démarrage pour Android
  ios: true # Activer l'écran de démarrage pour iOS
  web: false # Désactiver l'écran de démarrage pour le web
  image_size: "cover"
