// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP5KSSCtd0x1nCv5QNZuQZuZwR-rThSOA',
    appId: '1:867992731472:web:927925376ad42dedb27655',
    messagingSenderId: '867992731472',
    projectId: 'siahaty-41a5d',
    authDomain: 'siahaty-41a5d.firebaseapp.com',
    storageBucket: 'siahaty-41a5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIbG4o5p6t1cQO7953a-s9Qkvi-R7qFk',
    appId: '1:867992731472:android:b42fd2bcd90080afb27655',
    messagingSenderId: '867992731472',
    projectId: 'siahaty-41a5d',
    storageBucket: 'siahaty-41a5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXlxhnU6hrD3BlvxyqbPrUlgCO5na06RI',
    appId: '1:867992731472:ios:29132566db0d2c9db27655',
    messagingSenderId: '867992731472',
    projectId: 'siahaty-41a5d',
    storageBucket: 'siahaty-41a5d.appspot.com',
    iosBundleId: 'com.example.achrefSiaha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXlxhnU6hrD3BlvxyqbPrUlgCO5na06RI',
    appId: '1:867992731472:ios:29132566db0d2c9db27655',
    messagingSenderId: '867992731472',
    projectId: 'siahaty-41a5d',
    storageBucket: 'siahaty-41a5d.appspot.com',
    iosBundleId: 'com.example.achrefSiaha',
  );
}
